global:
  scrape_interval: 1m
  scrape_timeout: 10s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets:
          - "prometheus:9090"

  - job_name: "node"
    static_configs:
      - targets:
          - "node-exporter:9100"
  
  - job_name: "grafana"
    static_configs:
      - targets:
          - "grafana:3000"
